name: poliz
description: "A new Flutter project."
publish_to: 'none' # ไม่เผยแพร่ที่ pub.dev

# เวอร์ชันและหมายเลขบิลด์
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies สำหรับโปรเจกต์หลัก
dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^3.1.2
  http: ^1.2.0
  intl: ^0.20.2  # Make sure intl is included
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.8
  pdf: ^3.10.7
  printing: ^5.12.0

# Dependencies สำหรับการทดสอบ
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # หากต้องการใช้ assets
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # หากต้องการเพิ่มฟอนต์เอง
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
